version: '3.1'

services:
  reverse-proxy:
    image: nginx:1.22.1
    container_name: web_server
    depends_on:
      - backend
      - frontend
    ports:
      - 80:80
    volumes:
      - ./reverse_proxy/nginx.conf:/etc/nginx/nginx.conf
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5002:5002"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"