export let phrasesInit = [
  "(child noises in the background)",
  "Hello, hello?",
  "i need to jump in another call",
  "can everyone go on mute",
  "could you please get closer to the mic",
  "(load painful echo / feedback)",
  "Next slide, please",
  "can we take this offline?",
  "is ___ on the call?",
  "Could you share this slides afterwards?",
  "can somebody grant presenter rights?",
  "can you email that to everyone?",
  "conf call bingo",
  "i'll have to get back to you",
  "You will send the minutes?",
  "sorry, i had problems loging in",
  "(animal noises in the background)",
  "sorry, i didn't found the conference id",
  "i was having connection issues",
  "who just joined?",
  "sorry, something ___ with my calendar",
  "do you see my screen?",
  "lets wait for ___!",
  "sorry, i was on mute.",
  "can you repeat, please?",
];

export let gameRules = [
  "Do not Refresh the page.",
  "A player wins by completing a row, column, or diagonal.",
  "There's a free slot (always on) in the middle",
  "You can have multiple bingos",
  "A player wins after scoring 5 points",
];
